# Generated by Django 3.0.2 on 2020-01-04 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mstr_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_type', models.CharField(choices=[('new', '新規見積'), ('revise', '改定見積')], default='revise', max_length=10)),
                ('estimate_state', models.CharField(choices=[('making', '作成中'), ('printed', '印刷済み'), ('onnego', '商談中'), ('success', '商談成立'), ('failed', '失注')], default='making', max_length=10)),
                ('selling_price_type', models.CharField(choices=[('nai', '県内'), ('gai', '県外')], default='nai', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sls_prn', models.CharField(blank=True, max_length=300, null=True)),
                ('sls_rep', models.CharField(blank=True, max_length=300, null=True)),
                ('wholesale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='見積状態')),
                ('remarks_1', models.CharField(blank=True, default='上記価格に消費税は含まれておりません。', max_length=300, null=True)),
                ('remarks_2', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks_3', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks_4', models.CharField(blank=True, max_length=300, null=True)),
                ('internal_remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mstr_manage.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('selling_price_new', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('selling_price_old', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('wholesale_price_new', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('wholesale_price_old', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('wholesale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remarks', models.CharField(blank=True, max_length=32, null=True)),
                ('estmt_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.Estimate_header')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mstr_manage.Product')),
            ],
        ),
    ]
