# Generated by Django 3.0.2 on 2020-01-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_detail',
            name='selling_price_old',
        ),
        migrations.RemoveField(
            model_name='estimate_detail',
            name='wholesale_price_old',
        ),
        migrations.RemoveField(
            model_name='estimate_header',
            name='estimate_type',
        ),
        migrations.RemoveField(
            model_name='estimate_header',
            name='selling_price_type',
        ),
    ]
