# Generated by Django 3.0.2 on 2020-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_auto_20200107_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate_header',
            name='wholesale_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
