# Generated by Django 3.0.2 on 2020-01-09 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstr_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alias',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
